#!/usr/bin/env bash

# Name of the private key
private_key="school"

# Number of bits in the created key
key_bits=4096

# Create the RSA key pair with the specified name and number of bits
ssh-keygen -t rsa -b "$key_bits" -f "$private_key"

# Add passphrase to the private key
openssl rsa -in "${private_key}" -passout pass:betty -out "${private_key}.enc"
